### ISSUE TITLE
TypeError when creating RadarrMovie structure

### ISSUE THREAD

**Issue by ubiquitous42** [Navino16/Varken#5]
I think you have an api mismatch with Radarr.  Radarr reports a `releaseDate` for the `/api/v3/movie` endpoint, and I'm getting this error: `2024-10-05 04:52:01 : ERROR : radarr : TypeError has occurred : RadarrMovie.__new__() got an unexpected keyword argument 'releaseDate' while creating RadarrMovie structure`

**Comment by Navino16** [comment]
@ubiquitous42 fixed. Please pull last image
